# Ephemeral credential broker -- Makefile
#
# Standard kubebuilder-shaped targets. A few of these (manifests, generate)
# need controller-gen, and deploy/undeploy need kustomize; neither tool
# could be installed in the sandbox this project was scaffolded in (no
# network access to the Go module proxy), so config/crd, config/rbac, and
# api/v1alpha1/zz_generated.deepcopy.go were written by hand instead. Once
# you have normal internet access, `make manifests generate` should
# regenerate them as equivalent, machine-generated files.

IMG ?= ephemeral-credential-broker:dev
CONTROLLER_GEN ?= go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.16.5
KUSTOMIZE ?= go run sigs.k8s.io/kustomize/kustomize/v5@v5.4.3

.PHONY: all
all: build

.PHONY: manifests
manifests: ## Regenerate CRD/RBAC YAML from kubebuilder markers. Needs network access.
	$(CONTROLLER_GEN) rbac:roleName=ephemeral-credential-broker-manager-role crd webhook \
		paths="./..." \
		output:crd:artifacts:config=config/crd/bases

.PHONY: generate
generate: ## Regenerate zz_generated.deepcopy.go from kubebuilder markers. Needs network access.
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."

.PHONY: fmt
fmt:
	go fmt ./...

.PHONY: vet
vet:
	go vet ./...

.PHONY: test
test: fmt vet ## Unit tests. internal/provider/... needs no network or
                ## external deps and runs anywhere; api/... and
                ## internal/controller/... need `go mod tidy` to have run
                ## first (see go.mod).
	go test ./... -race -coverprofile cover.out

.PHONY: test-provider
test-provider: ## Just the dependency-free provider tests -- always runnable.
	go test ./internal/provider/... -v

.PHONY: build
build: fmt vet ## Build the manager binary.
	go build -o bin/manager cmd/main.go

.PHONY: run
run: fmt vet ## Run against the cluster your current kubeconfig points at.
	go run ./cmd/main.go

.PHONY: docker-build
docker-build: ## Build the controller image.
	docker build -t ${IMG} .

.PHONY: docker-push
docker-push:
	docker push ${IMG}

.PHONY: install
install: manifests ## Install the CRD into the cluster your kubeconfig points at.
	kubectl apply -f config/crd/bases

.PHONY: uninstall
uninstall: ## Remove the CRD (and, by extension, every EphemeralCredential).
	kubectl delete -f config/crd/bases --ignore-not-found

.PHONY: deploy
deploy: manifests ## Deploy the controller via kustomize. Needs docker-push'd IMG first.
	cd config/manager && $(KUSTOMIZE) edit set image ephemeral-credential-broker=${IMG}
	$(KUSTOMIZE) build config/default | kubectl apply -f -

.PHONY: undeploy
undeploy:
	$(KUSTOMIZE) build config/default | kubectl delete --ignore-not-found -f -

.PHONY: build-installer
build-installer: manifests ## Regenerate dist/install.yaml from config/.
	mkdir -p dist
	{ \
	  echo "# Regenerated by 'make build-installer'. Do not edit by hand." ; \
	  $(KUSTOMIZE) build config/default ; \
	} > dist/install.yaml

.PHONY: kind-load
kind-load: docker-build ## Build the image and load it straight into a kind cluster (no registry needed).
	kind load docker-image ${IMG}

.PHONY: envtest-setup
envtest-setup: ## One-time download of the kube-apiserver/etcd binaries envtest needs. No Docker/kind required.
	go run sigs.k8s.io/controller-runtime/tools/setup-envtest@latest use -p path

.PHONY: clean
clean:
	rm -rf bin cover.out
