//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
//
// NOTE: this sandbox could not install controller-gen (no network access to
// the Go module proxy -- see go.mod), so this file was written BY HAND to
// exactly match what `controller-gen object:headerFile=... paths=./...`
// would produce for the types in ephemeralcredential_types.go. Once you
// have controller-gen available, running `make generate` (see Makefile)
// will regenerate this file and it should come out equivalent; treat this
// hand-written version as a placeholder, not a substitute for regenerating.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSProviderConfig) DeepCopyInto(out *AWSProviderConfig) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new AWSProviderConfig.
func (in *AWSProviderConfig) DeepCopy() *AWSProviderConfig {
	if in == nil {
		return nil
	}
	out := new(AWSProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseProviderConfig) DeepCopyInto(out *DatabaseProviderConfig) {
	*out = *in
	out.AdminSecretRef = in.AdminSecretRef
	out.ConnectionRef = in.ConnectionRef
	if in.Grants != nil {
		in, out := &in.Grants, &out.Grants
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new DatabaseProviderConfig.
func (in *DatabaseProviderConfig) DeepCopy() *DatabaseProviderConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralCredential) DeepCopyInto(out *EphemeralCredential) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new EphemeralCredential.
func (in *EphemeralCredential) DeepCopy() *EphemeralCredential {
	if in == nil {
		return nil
	}
	out := new(EphemeralCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EphemeralCredential) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralCredentialList) DeepCopyInto(out *EphemeralCredentialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EphemeralCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new EphemeralCredentialList.
func (in *EphemeralCredentialList) DeepCopy() *EphemeralCredentialList {
	if in == nil {
		return nil
	}
	out := new(EphemeralCredentialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EphemeralCredentialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralCredentialSpec) DeepCopyInto(out *EphemeralCredentialSpec) {
	*out = *in
	in.TargetSecret.DeepCopyInto(&out.TargetSecret)
	in.ProviderConfig.DeepCopyInto(&out.ProviderConfig)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new EphemeralCredentialSpec.
func (in *EphemeralCredentialSpec) DeepCopy() *EphemeralCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(EphemeralCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralCredentialStatus) DeepCopyInto(out *EphemeralCredentialStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.LastRotatedAt != nil {
		in, out := &in.LastRotatedAt, &out.LastRotatedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new EphemeralCredentialStatus.
func (in *EphemeralCredentialStatus) DeepCopy() *EphemeralCredentialStatus {
	if in == nil {
		return nil
	}
	out := new(EphemeralCredentialStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubProviderConfig) DeepCopyInto(out *GitHubProviderConfig) {
	*out = *in
	out.AppConfigRef = in.AppConfigRef
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new GitHubProviderConfig.
func (in *GitHubProviderConfig) DeepCopy() *GitHubProviderConfig {
	if in == nil {
		return nil
	}
	out := new(GitHubProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfig) DeepCopyInto(out *ProviderConfig) {
	*out = *in
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(GitHubProviderConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSProviderConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(DatabaseProviderConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Vault != nil {
		in, out := &in.Vault, &out.Vault
		*out = new(VaultProviderConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ProviderConfig.
func (in *ProviderConfig) DeepCopy() *ProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSecretSpec) DeepCopyInto(out *TargetSecretSpec) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new TargetSecretSpec.
func (in *TargetSecretSpec) DeepCopy() *TargetSecretSpec {
	if in == nil {
		return nil
	}
	out := new(TargetSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultProviderConfig) DeepCopyInto(out *VaultProviderConfig) {
	*out = *in
	out.BackendRef = in.BackendRef
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new VaultProviderConfig.
func (in *VaultProviderConfig) DeepCopy() *VaultProviderConfig {
	if in == nil {
		return nil
	}
	out := new(VaultProviderConfig)
	in.DeepCopyInto(out)
	return out
}
